# Generated by Django 2.1.3 on 2018-11-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlocker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
    ]
