# Generated by Django 2.1.3 on 2018-11-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocker', '0002_auto_20181108_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='audio',
            field=models.FileField(null=True, upload_to='audios/'),
        ),
    ]
