# Generated by Django 2.0.9 on 2018-11-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocker', '0006_auto_20181110_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimerequest',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='thumbs/'),
        ),
        migrations.AlterField(
            model_name='onetimerequest',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
