# Generated by Django 2.0.9 on 2018-11-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocker', '0007_auto_20181110_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimerequest',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
